### ISSUE TITLE
HDF5 version requirement

### ISSUE THREAD

**Issue by wkliao** [HDFGroup/hdf5-iotest#22]
https://github.com/HDFGroup/hdf5-iotest/blob/462837bedb126210b5ac3b8e8f3ac2e4b0eef5b4/src/utils.c#L214

As HDF5 has released 1.14.0, this line of version number check raises an assertion.
```
hdf5_iotest: src/utils.c:214: set_libver_bounds:
Assertion `majnum == 1 && minnum >= 8 && minnum <= 13' failed.
``` 
Maybe the last condition "`&& minnum <= 13`" can be removed?

**Comment by wkliao** [comment]
Just to point out that the HDF5 develop branch has set the version to 1.15.0.
https://github.com/HDFGroup/hdf5/blob/509fe962d42b3f02d356d2668b04712df06daf7f/configure.ac#L25

So this line of github actions file main.yml which clones the branch develop may fail.
https://github.com/HDFGroup/hdf5-iotest/blob/462837bedb126210b5ac3b8e8f3ac2e4b0eef5b4/.github/workflows/main.yml#L58
Is there a reason to set an upper bound for minnum ?

**Comment by brtnfld** [comment]
It is a reminder that the library bounds need to be updated when a new 1.x release is made. It should work with 1.15 (develop).

**Comment by wkliao** [comment]
Hi, @brtnfld 
Could you please merge #23 to the master branch, so I can use it in the Log VOL tests?

**Comment by brtnfld** [comment]
Sorry about that. Done.

**Comment by wkliao** [comment]
Thanks, Scot !
